package util;

public enum View {
	HOME, ADMIN, MEMBER, SIGNIN, SIGNUP, FINDIDPW, FINDID, FINDPASS, SELECTSEAT, CHANGESEAT, CHARGETIME, ORDER, 
	INFO, INFOEDIT, INFODEL, MYCART, SIGNOUT,  
	MEMLIST, MEMEDIT, MEMDEL, PRODLIST, PRODADD, 
	PRODDEL, PRODORDER, ORDERLIST, CHECKORDER, INCOMPLITEORDER, SALES, MEMMANAGE, ADMINSIGNIN, COMPORDER, PRODUPDATE
}
